import type { GlobalThemeOverrides } from 'naive-ui'
import type { ThemePalette } from '../stores/theme'

export function createFoxThemeOverrides(palette: ThemePalette): GlobalThemeOverrides {
  return {
  common: {
    primaryColor: palette.primary,
    primaryColorHover: palette.hover,
    primaryColorPressed: palette.strong,
    primaryColorSuppl: palette.supplement,
    infoColor: palette.primary,
    infoColorHover: palette.hover,
    infoColorPressed: palette.strong,
    successColor: '#16a34a',
    successColorHover: '#22c55e',
    successColorPressed: '#15803d',
    warningColor: '#f59e0b',
    warningColorHover: '#fbbf24',
    warningColorPressed: '#d97706',
    errorColor: '#dc2626',
    errorColorHover: '#ef4444',
    errorColorPressed: '#b91c1c',
    bodyColor: '#f6f8fc',
    cardColor: '#ffffff',
    modalColor: '#ffffff',
    popoverColor: '#ffffff',
    textColorBase: '#0f172a',
    textColor1: '#111827',
    textColor2: '#475569',
    textColor3: '#64748b',
    borderColor: '#dfe7f2',
    dividerColor: '#edf1f7',
    hoverColor: palette.surfaceHover,
    borderRadius: '6px',
    borderRadiusSmall: '5px',
  },
  Button: {
    borderRadiusTiny: '5px',
    borderRadiusSmall: '5px',
    borderRadiusMedium: '6px',
    borderRadiusLarge: '6px',
    fontWeight: '600',
  },
  Card: {
    borderRadius: '8px',
    color: '#ffffff',
    borderColor: '#e5ebf5',
    titleTextColor: '#111827',
  },
  Checkbox: {
    borderRadius: '4px',
  },
  Input: {
    borderRadius: '6px',
    borderHover: `1px solid ${palette.borderActive}`,
    borderFocus: `1px solid ${palette.primary}`,
    boxShadowFocus: `0 0 0 2px ${palette.focusShadow}`,
  },
  Layout: {
    color: '#f6f8fc',
    siderColor: '#ffffff',
    headerColor: '#ffffff',
  },
  Menu: {
    itemBorderRadius: '6px',
    itemColorActive: palette.soft,
    itemColorActiveHover: palette.softHover,
    itemColorHover: palette.surfaceHover,
    itemIconColor: '#334155',
    itemIconColorActive: palette.primary,
    itemTextColor: '#1f2937',
    itemTextColorActive: palette.primary,
  },
}
}
